// Tailwind Play CDN config (must load before https://cdn.tailwindcss.com)
window.tailwind = window.tailwind || {};
window.tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background-light": "#f6f7f8",
        "background-dark": "#121920",
        "surface-dark": "#1a232e",
        "on-surface-dark": "#e2e8f0",
        "outline-variant": "#acb3b7",
        "surface-container-low": "#f0f4f7",
        outline: "#747c80",
        "secondary-fixed": "#d7e3f8",
        "tertiary-dim": "#564d77",
        "on-primary": "#f7f9ff",
        "surface-variant": "#dce4e8",
        "inverse-surface": "#0b0f10",
        primary: "#0A2540",
        "on-secondary-fixed-variant": "#515c6d",
        "on-secondary-container": "#475363",
        "on-primary-container": "#334b67",
        surface: "#f7f9fb",
        "on-primary-fixed": "#1f3753",
        "on-surface": "#2c3437",
        error: "#a83836",
        "surface-tint": "#49617f",
        "on-tertiary-fixed-variant": "#514972",
        "on-primary-fixed-variant": "#3d5471",
        "surface-container-highest": "#dce4e8",
        "on-tertiary": "#fdf7ff",
        "inverse-primary": "#bed6f9",
        "tertiary-container": "#d3c8f9",
        "secondary-container": "#d7e3f8",
        "secondary-fixed-dim": "#c9d5e9",
        "on-error-container": "#6e0a12",
        "primary-fixed-dim": "#b0c8eb",
        "on-surface-variant": "#596064",
        "primary-dim": "#3d5572",
        "inverse-on-surface": "#9a9d9f",
        background: "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "tertiary-fixed-dim": "#c5baeb",
        "error-dim": "#67040d",
        "surface-container-high": "#e3e9ed",
        "on-tertiary-fixed": "#342c54",
        "surface-dim": "#d4dbdf",
        "on-secondary-fixed": "#344050",
        "on-background": "#2c3437",
        "on-error": "#fff7f6",
        "surface-container": "#eaeff2",
        "on-tertiary-container": "#484068",
        "primary-container": "#bed6f9",
        "surface-container-lowest": "#ffffff",
        tertiary: "#625983",
        "secondary-dim": "#485465",
        "on-secondary": "#f7f9ff",
        "primary-fixed": "#bed6f9",
        "tertiary-fixed": "#d3c8f9",
        secondary: "#546071",
        "error-container": "#fa746f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"],
      },
    },
  },
};
